% Generate random points in region [0, 10] * [0, 1] and apply a sigmoid
% function to the y-coordinates
[x, y] = random_points(0, 10, 0, 1, 200);
y = y + 5 * sigmoid(x, 5, 1.4);

% Plot the points
scatter(x, y, 16);%, 3, "filled");

% Run the regression algorithm
lambda = 0.01;
[x_out, beta] = piecewise_linearreg([x y], lambda);

% Transform outputs
y_out = mxb_to_endpoints(x_out, beta);

% Plot the lines generated by the regression algorithm
line(x_out', y_out', 'Color', 'red', 'LineWidth', 2);

% Add labels
title(strcat('Piecewise Linear Regression, λ = ', num2str(lambda)));
xlabel('x');
ylabel('y');